# Generated by Django 3.0.2 on 2020-01-06 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Videoclub',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=25)),
                ('nombre_gerente', models.CharField(max_length=50)),
                ('ciudad', models.CharField(max_length=50)),
                ('calle', models.CharField(max_length=50)),
                ('codigo_postal', models.CharField(max_length=5)),
            ],
        ),
    ]
