# Generated by Django 3.0.2 on 2020-01-06 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_videoclub'),
    ]

    operations = [
        migrations.CreateModel(
            name='Peliculas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=25)),
                ('director', models.CharField(max_length=25)),
                ('fecha_de_estreno', models.DateField(max_length=25)),
                ('precio_alquiler', models.FloatField(max_length=25)),
            ],
        ),
    ]
