# Generated by Django 3.0.2 on 2020-01-06 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_peliculas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Socios',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=25)),
                ('edad', models.IntegerField(max_length=25)),
            ],
        ),
    ]
