# Generated by Django 3.0.2 on 2020-01-07 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_administrador'),
    ]

    operations = [
        migrations.AddField(
            model_name='peliculas',
            name='key',
            field=models.ForeignKey(default='', editable=False, on_delete=django.db.models.deletion.CASCADE, to='polls.Videoclub'),
        ),
        migrations.AddField(
            model_name='peliculas',
            name='videoclub_dato',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AddField(
            model_name='socios',
            name='email',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AddField(
            model_name='socios',
            name='sexo',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AddField(
            model_name='socios',
            name='videoclub',
            field=models.CharField(default='', max_length=25),
        ),
    ]
