# Generated by Django 3.0.2 on 2020-01-07 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_auto_20200107_0749'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socios',
            name='videoclub',
        ),
    ]
