# Generated by Django 3.0.2 on 2020-01-07 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_remove_socios_videoclub'),
    ]

    operations = [
        migrations.AddField(
            model_name='alquileres',
            name='nombre',
            field=models.CharField(default='', max_length=25),
        ),
    ]
